version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
