apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kingoftheheap-dev-tls
  namespace: default
spec:
  secretName: kingoftheheap-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - skny.link
  - www.skny.link