apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: url-shortener-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shortener-app
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
