apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortener-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - skny.link
    - www.skny.link
    secretName: kingoftheheap-dev-tls
  rules:
  - host: skny.link
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: url-shortener-app
            port:
              number: 8080
      - path: /
        pathType: Exact
        backend:
          service:
            name: skny-link-frontend
            port:
              number: 80
      - path: / # catch-all rule for shortened URLs
        pathType: Prefix
        backend:
          service:
            name: url-shortener-app
            port:
              number: 8080
  - host: www.skny.link
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: url-shortener-app
            port:
              number: 8080
      - path: /
        pathType: Exact
        backend:
          service:
            name: skny-link-frontend
            port:
              number: 80
      - path: / # catch-all rule for shortened URLs
        pathType: Prefix
        backend:
          service:
            name: url-shortener-app
            port:
              number: 8080
